baseurl = "/"
languageCode = "en-us"
theme = ""
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems =3
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "Sooraj Nhaloor"
   # subtitle = ""
   # keywords = ""
    copyright = ""
   # menuMore = "Show more"
    #writtenBy = "Written by"
    #readMore = "Read more"
    #readOtherPosts = "Read other posts"
    #newerPosts = "Newer posts"
    #olderPosts = "Older posts"
    #minuteReadingTime = "min read"
    #dateFormatSingle = "2006-01-02"
    #dateFormatList = "2006-01-02"
    

    [languages.en.params.logo]
      logoText = "Sooraj Nhaloor"
      intro = " Hello there ! "
      subtitle = ""
      content = "this is content"
      logoHomeLink = "/"
      
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
     [[languages.en.menu.main]]
        identifier = "home"
        name = " Home"
        url = "/"
    
      [[languages.en.menu.main]]
        identifier = "cv"
        name = "CV"
        url = "/cv"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
